apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: go-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app

    spec:
      containers:
      - name: go-app
        image: public.ecr.aws/z5v0g9o1/devops-project:latest
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: go_app-service
spec:
  selector:
    app: go-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
