name: CI

on: 
  push:
     branches: main

jobs:
    build:
      if: github.event.pull.merged == true || ${{ github.event.head_commit.message }} == 'BUILD_CONTAINER_IMAGE'
      name: build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: login to dockerhub
        run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "anniruddh09" --password-stdin

      - name: build and push the image
        run: |
             docker build -t anniruddh09/go-app:latest .
             docker push anniruddh09/go-app:latest
