name: CI

on: 
  push:
     branches: main

jobs:
    build:

      name: build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: login to dockerhub
        run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "anniruddh09" --password-stdin

      - name: build and push the image
        run: docker build -t anniruddh09/go-app:$(date +%s) .
        
      - name: Docker Push
        run: docker push anniruddh09/go-app:$(date +%s)
