name: CI

on: 
  push:
     branches: main

jobs:
    build:

      name: build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: login to dockerhub
        env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
            docker login -u ${{ DOCKER_USER }} -p $DOCKER_PASSWORD

      - name: build and push the image
        run: docker build -t anniruddh09/gop-app:$(date +%s) .
        
      - name: Docker Push
        run: docker push anniruddh09/gop-app:$(date +%s)
