name: CI

on: 
  push:
     branches: main

jobs:
    build:

      name: build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: login to dockerhub
        env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
            docker login -u ${{ secrets.DOCKER_USER }} -p $DOCKER_PASSWORD

      - name: build and push the image
        run: docker build . --file Dockerfile --tag anniruddh09/sample_image:$(date +%s)
        
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USER }}/go-app
