name: CI

on: 
  push:
     branches: main

jobs:
    build:

      name: build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: login to dockerhub
        env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
            docker login -u $DOCKER_USER -p $DOCKERHUB_PASSWORD

      - name: build and push the image
        run: docker build . --file Dockerfile --tag anniruddh/go-app:$(date +%s)
        
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USER }}/go-app
